// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATY2ZcCxezugSx_45RxDtrl13-aW5bzbE',
    appId: '1:769710441251:web:ff83933d03e6064e954296',
    messagingSenderId: '769710441251',
    projectId: 'tobbydo-ad82d',
    authDomain: 'tobbydo-ad82d.firebaseapp.com',
    storageBucket: 'tobbydo-ad82d.appspot.com',
    measurementId: 'G-00RRFLXZG8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANqC2HIg_-b_rRlyHq1EuHnk9gtJerXT8',
    appId: '1:769710441251:android:b9b9b062b932acec954296',
    messagingSenderId: '769710441251',
    projectId: 'tobbydo-ad82d',
    storageBucket: 'tobbydo-ad82d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu_AzJDRJ1XNKqjkJoYS0ZhSCQ46-cACg',
    appId: '1:769710441251:ios:9da0790c64d7f58b954296',
    messagingSenderId: '769710441251',
    projectId: 'tobbydo-ad82d',
    storageBucket: 'tobbydo-ad82d.appspot.com',
    iosClientId: '769710441251-a9eu8cudf4g735p65hidc8agv4gu0npg.apps.googleusercontent.com',
    iosBundleId: 'com.example.tobbyDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu_AzJDRJ1XNKqjkJoYS0ZhSCQ46-cACg',
    appId: '1:769710441251:ios:164a7d4330ee5b59954296',
    messagingSenderId: '769710441251',
    projectId: 'tobbydo-ad82d',
    storageBucket: 'tobbydo-ad82d.appspot.com',
    iosClientId: '769710441251-jcdf4s6040mooojnn97leputaqh2ca0g.apps.googleusercontent.com',
    iosBundleId: 'com.example.tobbyDo.RunnerTests',
  );
}
